env:
  - DOCKER_COMPOSE_VERSION=1.21.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
  - stage: build docker image with tag
    if: branch = master AND tag =~ ^v
    script:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - docker build -t rabinzon/read_quran --file services/app/Dockerfile.prod services/app/
    - docker push rabinzon/read_quran:"$TRAVICE_TAG"

notifications:
  slack:
    secure: $SLACK_TOKEN
