version: '3.3'

services:
  app:
    environment:
      - DATABASE_URL=postgres://admin:postgres@postgres:5432/postgres
      - NODE_ENV=test

    build:
      context: .
      dockerfile: Dockerfile.production
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app:rw"
      - "/usr/src/app/node_modules"
    command: "make migrate check"
    ports:
      - "3000:3000"
    networks:
      - services
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_URL=postgres://admin:postgres@postgres:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres

    networks:
      - services

networks:
  services:
    driver: bridge
