version: '3.3'

services:
  app:
    environment:
      - DATABASE_URL=postgres://admin:postgres@postgres:5432/postgres
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./:/usr/src/app:rw"
    command: "make migrate test"
    ports:
      - "3000:3000"
    networks:
      - services
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_URL=postgres://admin:postgres@postgres:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    networks:
      - services

networks:
  services:
    driver: bridge
